---
title: "Review results"
author: "Jerome Hilaire"
date: "5 Juli 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r init_data, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE}
#==== Initialise =============================
library(dplyr)
library(tidyr)
library(ggplot2)
source("get_statement_categories.R")
source("process_statement_review_data.R")


#==== Get data ===============================
# Get categories
cat <- get_statement_categories()

# Get data
data_all   <- process_statement_review_data(u_path_pars, u_path_notestat, u_path_alldoc)
pars       <- data_all[["pars"]]
note_stats <- data_all[["note_stats"]]
all        <- data_all[["all"]]
all_simple <- data_all[["all_simple"]]
```

## Number of statements
```{r compute_nb_stat, echo=FALSE, message=FALSE, warning=FALSE}
nb_stat <- note_stats %>% 
  filter(!duplicated(docstatement__text)) %>% 
  summarise(count=n())
```
`r nb_stat$count` statements were extracted from the scenario literature.

## Number of statements by relevance
```{r compute_nb_stat_by_cat, echo=FALSE, message=FALSE, warning=FALSE}
nb_stat_by_cat <- note_stats %>% 
  mutate(category1=unlist(sapply(docstatement__technology__name,
                         function(x) {
                           techs <- sapply(strsplit(names(unlist(cat)), ".", fixed=TRUE), function(y) y[2])
                           out <- paste(unlist(cat))[which(substr(x,1,2) == techs)]
                           out <- ifelse(length(out)== 0, "", out)
                           return(out)
                         }))) %>% 
  mutate(category2=unlist(sapply(docstatement__technology__name,
                         function(x) {
                           techs <- sapply(strsplit(names(unlist(cat)), ".", fixed=TRUE), function(y) y[2])
                           out <- names(unlist(cat))[which(substr(x,1,2) == techs)]
                           out <- ifelse(length(out)== 0, "", out)
                           tryCatch(
                             out <- strsplit(out, ".", fixed=TRUE)[[1]][1],
                             error=function(e){
                               out <- ""
                             }  
                           )
                           
                           return(out)
                         }))) %>%            
  group_by(category1, category2) %>% 
  filter(!duplicated(docstatement__text)) %>% 
  summarise(count=n()) %>% 
  ungroup()
```

```r{table1}
kable(nb_stat_by_cat)
```

## Number of statements by category
```{r compute_nb_stat_by_cat, echo=FALSE, message=FALSE, warning=FALSE}
nb_stat_by_cat <- note_stats %>% 
  mutate(category1=unlist(sapply(docstatement__technology__name,
                         function(x) {
                           techs <- sapply(strsplit(names(unlist(cat)), ".", fixed=TRUE), function(y) y[2])
                           out <- paste(unlist(cat))[which(substr(x,1,2) == techs)]
                           out <- ifelse(length(out)== 0, "", out)
                           return(out)
                         }))) %>% 
  mutate(category2=unlist(sapply(docstatement__technology__name,
                         function(x) {
                           techs <- sapply(strsplit(names(unlist(cat)), ".", fixed=TRUE), function(y) y[2])
                           out <- names(unlist(cat))[which(substr(x,1,2) == techs)]
                           out <- ifelse(length(out)== 0, "", out)
                           tryCatch(
                             out <- strsplit(out, ".", fixed=TRUE)[[1]][1],
                             error=function(e){
                               out <- ""
                             }  
                           )
                           
                           return(out)
                         }))) %>%            
  group_by(category1, category2) %>% 
  filter(!duplicated(docstatement__text)) %>% 
  summarise(count=n()) %>% 
  ungroup()
```

```r{table1}
kable(nb_stat_by_cat)
```



## Number of statements by category over time



```{r cars}
summary(cars)
```
